# Generated by Django 2.2 on 2020-04-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emiten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emiten_code', models.TextField(blank=True, db_column='emiten_code', null=True)),
                ('emiten_name', models.TextField(blank=True, db_column='emiten_name', null=True)),
            ],
            options={
                'db_table': 'emiten',
                'ordering': ['emiten_code'],
            },
        ),
        migrations.CreateModel(
            name='TbpTable2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_column='title', null=True)),
                ('source', models.TextField(blank=True, db_column='source', null=True)),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('paragraph', models.TextField(blank=True, db_column='paragraph', null=True)),
                ('emiten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nbapp.Emiten')),
            ],
            options={
                'db_table': 'tbp_table2',
            },
        ),
    ]
